debug= false
blacklisted_games = []

[steamgrid_db]
auth_key = "Write your authentication key between these quotes"
enabled = true
prefer_animated = false

[origin]
enabled = true
prepend = false

[gog]
enabled = true
create_symlinks = true

[epic_games]
enabled = true
create_symlinks = true
safe_launch = []

[uplay]
enabled = true
prepend = false

[legendary]
enabled = true

[itch]
enabled = true
create_symlinks = true

[lutris]
enabled = false

[heroic]
enabled = true

[amazon]
enabled = true
prepend = false

[steam]
create_collections = false
optimize_for_big_picture = false
stop_steam = false
start_steam = false
